// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import { render, screen, cleanup } from '@testing-library/react';
import { test, expect, vi, afterEach } from 'vitest';
import { CollectionDirectory } from './CollectionDirectory';
const mock=vi.hoisted(()=>({get:vi.fn()}));
vi.mock('./collection-data.mjs',()=>({createNFTCollectionData:()=>mock.get}));
const address='0xe3b34C4bb0f12C82143745EEe6A6Cf4E3154b1fa' as const;
const collections=[{address,name:'Cash Cats',slug:'cash-cats',image:'',enabled:true}];
afterEach(()=>{cleanup();vi.unstubAllGlobals()});
test('shows logo, sourced trading volume and explicitly delayed data',async()=>{mock.get.mockResolvedValue({collections:[{address,volume24hUSD:5192.79,floorETH:.031,owners:3179,fetchedAt:'2026-09-11T00:00:00Z',status:'delayed',sourceURL:'https://www.coingecko.com/en/nft/cashcatss'}]});const{container}=render(<CollectionDirectory collections={collections} onRequests={()=>{}}/>);expect(await screen.findByText('$5,193')).toBeVisible();expect(screen.getByText('0.031 ETH')).toBeVisible();expect(screen.getByText('3,179')).toBeVisible();expect(screen.getByText(/Update delayed/)).toBeVisible();expect(screen.getByRole('link',{name:'CoinGecko'})).toHaveAttribute('href','https://www.coingecko.com/en/nft/cashcatss');expect(container.querySelector('img')).toHaveAttribute('src','/brand/nft-collections/cash-cats.png')});
test('unavailable market data does not hide the collection or invent zero volume',async()=>{mock.get.mockRejectedValue(Error('offline')); render(<CollectionDirectory collections={collections} onRequests={()=>{}}/>);expect(await screen.findByText('Market data unavailable')).toBeVisible();expect(screen.getByRole('heading',{name:'Cash Cats'})).toBeVisible();expect(screen.getAllByText('—')).toHaveLength(3);expect(screen.queryByText('$0')).not.toBeInTheDocument()});
test('shows Punks separately and opens requests for the correct collection',async()=>{const punk={address:'0xF08c65564eB07d880021105489552080b08e4319' as const,name:'Robinhood Punks',slug:'robinhood-punks',image:'',enabled:true};mock.get.mockResolvedValue({collections:[{address:punk.address,volume24hUSD:2121,floorETH:.007,owners:2007,fetchedAt:'2026-09-11T00:00:00Z',status:'current',sourceURL:'https://www.coingecko.com/en/nft/robinhood-punks'}]});const onRequests=vi.fn();const{container}=render(<CollectionDirectory collections={[...collections,punk]} onRequests={onRequests}/>);expect(await screen.findByText('$2,121')).toBeVisible();expect(screen.getByRole('link',{name:'CoinGecko'})).toHaveAttribute('href','https://www.coingecko.com/en/nft/robinhood-punks');const rows=container.querySelectorAll('article');expect(rows).toHaveLength(2);expect(rows[1].querySelector('img')).toHaveAttribute('src','/brand/nft-collections/robinhood-punks.png');rows[1].querySelector('button')!.click();expect(onRequests).toHaveBeenCalledWith(punk.address)});
