import test from 'node:test';import assert from 'node:assert/strict';import {encodeEventTopics,encodeAbiParameters} from 'viem';
import {checkImpact,quoteWithinBudget} from '../src/quote.mjs';import {BuybackWorker,abi,verifyBurn} from '../src/worker.mjs';import{Store}from'../../liquidator/src/store.mjs';
const addr='0x1111111111111111111111111111111111111111',module='0x2222222222222222222222222222222222222222';
function base(){const store=new Store(':memory:',{test:true});store.acquireLease();let signed=0,broadcast=0;const client={readContract:async()=>1000000n,getTransactionCount:async()=>0,getBalance:async()=>1000000000n,simulateContract:async()=>({}),sendRawTransaction:async()=>{broadcast++;throw Error('timeout');}};const worker=new BuybackWorker({store,client,verify:async()=>({number:100n}),account:{address:addr,signTransaction:async()=>{signed++;return '0x1234';}},wallet:{prepareTransactionRequest:async()=>({chainId:4663,type:'legacy',to:module,data:'0x',value:0n,gas:100n,gasPrice:1n,nonce:0})},config:{mode:'execute',module,maxTxFee:100000n,maxDailyGas:1000000n,minEth:0n},quote:async()=>{throw Error('quote_missing');}});return {worker,store,client,get signed(){return signed},get broadcast(){return broadcast}};}
function execution(){return {callTarget:addr,approveTarget:'0x0000000000000000000000000000000000000000',targetData:'0x12345678',clientData:'0x',desc:{srcToken:addr,dstToken:module,srcReceivers:[addr],srcAmounts:[1000000n],feeReceivers:[],feeAmounts:[],dstReceiver:module,amount:1000000n,minReturnAmount:1n,flags:512n,permit:'0x'}};}
test('impact comparison rejects deteriorated execution rate',()=>{checkImpact(100n,990n,10n,100n);assert.throws(()=>checkImpact(100n,989n,10n,100n));});
test('observe mode never quotes, signs, or broadcasts',async()=>{const t=base();t.worker.config.mode='observe';assert.equal((await t.worker.cycle()).reason,'observe_ready');assert.equal(t.signed,0);assert.equal(t.broadcast,0);t.store.close();});
test('below threshold never signs',async()=>{const t=base();t.client.readContract=async()=>999999n;assert.equal((await t.worker.cycle()).reason,'waiting_for_hour_balance_or_allowance');assert.equal(t.signed,0);t.store.close();});
test('verification failure happens before any quote or signing',async()=>{const t=base();t.worker.verify=async()=>{throw Error('bad_hash')};await assert.rejects(t.worker.cycle(),/bad_hash/);assert.equal(t.signed,0);t.store.close();});
test('uncertain send persists intent and reuses identical signed bytes',async()=>{const t=base();t.worker.quote=async()=>({amount:1000000n,execution:execution(),deadline:BigInt(Math.floor(Date.now()/1000)+60)});assert.equal((await t.worker.cycle()).reason,'broadcast_uncertain');const tx=t.store.pendingTx();assert(tx?.raw);assert.equal(t.signed,1);t.client.getTransactionReceipt=async()=>{const e=Error();e.name='TransactionReceiptNotFoundError';throw e};assert.equal((await t.worker.cycle()).reason,'broadcast_uncertain');assert.equal(t.store.pendingTx().hash,tx.hash);assert.equal(t.signed,1);assert.equal(t.broadcast,2);t.store.close();});
test('unknown nonce consumption blocks further submission',async()=>{const t=base();t.store.saveTx({id:'x',hash:'0xabc',raw:'0x1234',nonce:0,status:'pending',createdAt:Date.now()});t.client.getTransactionReceipt=async()=>{const e=Error();e.name='TransactionReceiptNotFoundError';throw e};t.client.getTransactionCount=async()=>1;assert.equal((await t.worker.cycle()).reason,'nonce_consumed_without_receipt');assert.equal(t.store.pendingTx().status,'blocked');assert.equal(t.broadcast,0);t.store.close();});
test('receipt needs exactly one matching positive burn event',()=>{const log={address:module,topics:encodeEventTopics({abi,eventName:'BoughtAndBurned'}),data:encodeAbiParameters([{type:'uint256'},{type:'uint256'},{type:'uint256'}],[100n,20n,1000n])};assert.equal(verifyBurn({logs:[log]},module,100n).turretBurned,20n);assert.throws(()=>verifyBurn({logs:[]},module,100n));assert.throws(()=>verifyBurn({logs:[log,log]},module,100n));assert.throws(()=>verifyBurn({logs:[log]},module,101n));});

test('impact-limited quote halves the amount without relaxing the guard',async()=>{const seen=[];const q=await quoteWithinBudget(module,8000000n,async(_,amount)=>{seen.push(amount);if(amount>2000000n)throw Error('price_impact_exceeds_one_percent');return {amount};});assert.deepEqual(seen,[8000000n,4000000n,2000000n]);assert.equal(q.amount,2000000n);});
test('quote downsizing is bounded and never retries an unrelated validation failure',async()=>{let attempts=0;await assert.rejects(quoteWithinBudget(module,1000000000n,async()=>{attempts++;throw Error('router_mismatch')}),/router_mismatch/);assert.equal(attempts,1);attempts=0;await assert.rejects(quoteWithinBudget(module,100000000000n,async()=>{attempts++;throw Error('price_impact_exceeds_one_percent')}),/no_size_within/);assert.equal(attempts,8);});
test('worker journals the smaller executed amount, not the hourly maximum',async()=>{const t=base();t.client.readContract=async()=>8000000n;t.worker.quote=async()=>({amount:1000000n,execution:execution(),deadline:BigInt(Math.floor(Date.now()/1000)+60)});await t.worker.cycle();assert.equal(t.store.pendingTx().amount,1000000n);t.store.close();});
test('quote cannot exceed contract budget or disagree with execution amount',async()=>{const t=base();t.worker.quote=async()=>({amount:2000000n,execution:execution(),deadline:BigInt(Math.floor(Date.now()/1000)+60)});await assert.rejects(t.worker.cycle(),/quote_amount_outside_budget/);assert.equal(t.signed,0);t.store.close();});

test('429 cooldown survives worker replacement and retries with a fresh quote without signing',async()=>{
 const t=base();let now=1000000,calls=0;t.worker.now=()=>now;
 t.worker.quote=async()=>{calls++;const e=Error('quote_rate_limited');e.retryAfterMs=120000;throw e;};
 const first=await t.worker.cycle();assert.equal(first.reason,'quote_rate_limited');assert.equal(first.nextRetryAt,now+120000);assert.equal(calls,1);assert.equal(t.signed,0);
 const replacement=new BuybackWorker({...t.worker});now+=60000;assert.equal((await replacement.cycle()).reason,'quote_retry_wait');assert.equal(calls,1);
 now+=60000;assert.equal((await replacement.cycle()).reason,'quote_rate_limited');assert.equal(calls,2);assert.equal(t.signed,0);assert.equal(t.broadcast,0);t.store.close();
});
test('validation failures are not converted into rate-limit retries',async()=>{
 const t=base();t.worker.quote=async()=>{throw Error('router_mismatch');};await assert.rejects(t.worker.cycle(),/router_mismatch/);assert.equal(t.store.get('quoteRetry'),undefined);assert.equal(t.signed,0);t.store.close();
});
test('rate limiting preserves downsizing progress, then requotes within the latest budget',async()=>{
 const t=base();let now=1000000,budget=24000000n,limited=true;const seen=[];t.worker.now=()=>now;t.client.readContract=async()=>budget;
 t.worker.quote=(m,b)=>quoteWithinBudget(m,b,async(_,amount)=>{seen.push(amount);if(amount>3000000n)throw Error('price_impact_exceeds_one_percent');if(limited){const e=Error('quote_rate_limited');e.retryAfterMs=60000;throw e;}return {amount,execution:{...execution(),desc:{...execution().desc,amount,srcAmounts:[amount]}},deadline:BigInt(Math.floor(Date.now()/1000)+60)};});
 assert.equal((await t.worker.cycle()).reason,'quote_rate_limited');assert.deepEqual(seen,[24000000n,12000000n,6000000n,3000000n]);assert.equal(t.store.get('quoteRetry').candidateAmount,3000000n);assert.equal(t.signed,0);
 limited=false;budget=2000000n;now+=60000;assert.equal((await t.worker.cycle()).reason,'broadcast_uncertain');assert.equal(seen.at(-1),2000000n);assert.equal(t.store.pendingTx().amount,2000000n);assert.equal(t.signed,1);assert.equal(t.store.get('quoteRetry'),null);t.store.close();
});

test('full-budget worker rejects a smaller amount before signing',async()=>{const t=base();t.worker.config.sizingPolicy='full-budget';t.client.readContract=async()=>60300000n;t.worker.quote=async()=>({amount:1000000n,execution:execution(),deadline:BigInt(Math.floor(Date.now()/1000)+60)});await assert.rejects(t.worker.cycle(),/quote_amount_outside_budget/);assert.equal(t.signed,0);assert.equal(t.broadcast,0);t.store.close();});
test('full-budget mode ignores an old downsized retry candidate and requotes the live budget',async()=>{const t=base();t.worker.config.sizingPolicy='full-budget';t.client.readContract=async()=>60300000n;t.store.set('quoteRetry',{failures:1,nextRetryAt:0,candidateAmount:3000000n});let requested;t.worker.quote=async(_,budget)=>{requested=budget;throw Error('test_stop_before_signing');};await assert.rejects(t.worker.cycle(),/test_stop_before_signing/);assert.equal(requested,60300000n);assert.equal(t.signed,0);t.store.close();});
