// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import {cleanup, fireEvent, render, screen} from '@testing-library/react';
import {afterEach, expect, test, vi} from 'vitest';
import {RequestCollateralPicker} from './RequestCollateralPicker';
import type {Deployment} from '../../p2p/client';
import admissions from '../../p2p/memecoin-admissions.json';
afterEach(cleanup);
const a={address:'0x1111111111111111111111111111111111111111',version:2,chainId:4663,collateralToken:'0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',collateralSymbol:'AAPL',collateralName:'Apple • Robinhood Token'} as Deployment;
const b={...a,address:'0x2222222222222222222222222222222222222222',collateralToken:'0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',collateralSymbol:'MSFT',collateralName:'Microsoft • Robinhood Token'} as Deployment;
function open(markets=[a,b], extra={}){const onChange=vi.fn();render(<RequestCollateralPicker markets={markets} value={a.address} disabled={false} onChange={onChange} {...extra}/>);fireEvent.click(screen.getByRole('button',{name:/Request collateral/}));return onChange;}
test('searches full names and selects the exact market with the keyboard',()=>{const change=open();const input=screen.getByRole('combobox');fireEvent.change(input,{target:{value:'microsoft'}});expect(screen.getAllByRole('option')).toHaveLength(1);fireEvent.keyDown(input,{key:'Enter'});expect(change).toHaveBeenCalledWith(b.address);expect(screen.queryByRole('listbox')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:/Request collateral/})).toHaveFocus();});
test('searches collateral addresses, including duplicate symbols',()=>{const change=open([a,{...b,collateralSymbol:'AAPL'}]);fireEvent.change(screen.getByRole('combobox'),{target:{value:b.collateralToken}});fireEvent.click(screen.getByRole('option'));expect(change).toHaveBeenCalledWith(b.address);});
test('Escape cancels without changing selection or dismissing the parent',()=>{const bubble=vi.fn(),change=vi.fn();render(<div onKeyDown={bubble}><RequestCollateralPicker markets={[a,b]} value={a.address} disabled={false} onChange={change}/></div>);fireEvent.click(screen.getByRole('button',{name:/Request collateral/}));fireEvent.keyDown(screen.getByRole('combobox'),{key:'Escape'});expect(change).not.toHaveBeenCalled();expect(bubble).not.toHaveBeenCalled();expect(screen.queryByRole('listbox')).not.toBeInTheDocument();});
test('empty search cannot submit and offers recovery',()=>{const change=open();const input=screen.getByRole('combobox');fireEvent.change(input,{target:{value:'not-an-asset'}});fireEvent.keyDown(input,{key:'Enter'});expect(change).not.toHaveBeenCalled();expect(screen.getByText('No matching collateral')).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Show all assets'}));expect(screen.getAllByRole('option')).toHaveLength(2);});
test('category filtering uses admitted market identity rather than its symbol',()=>{const entry=admissions.entries.find(e=>e.symbol==='PONS')!;const p={...a,version:3,address:entry.manager,collateralToken:entry.collateral,collateralSymbol:entry.symbol,collateralDecimals:entry.decimals,loanDecimals:6,loanToken:'0x5fc5360d0400a0fd4f2af552add042d716f1d168'} as Deployment;open([a,p]);fireEvent.click(screen.getByRole('button',{name:'Memecoins'}));expect(screen.getAllByRole('option')).toHaveLength(1);expect(screen.getByRole('option')).toHaveTextContent('PONS');fireEvent.click(screen.getByRole('button',{name:'Stocks & funds'}));expect(screen.getByRole('option')).toHaveTextContent('AAPL');});
test('disabled picker cannot change collateral during signing',()=>{open([a,b],{disabled:true});expect(screen.queryByRole('combobox')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:/Request collateral/})).toBeDisabled();});
